config/routes.rb
Rails.application.routes.draw do
  get '/' => 'dojos#index'
  get 'dojos/new' => 'dojos#new'
  post 'dojos/create' => 'dojos#create'
  get 'dojos/:id' => 'dojos#show', as: 'dojos_show'
  get 'dojos/:id/edit' => 'dojos#edit', as: 'dojos_edit'
  patch 'dojos/:id/edit' => 'dojos#update', as: 'dojos_update'
  delete 'dojos/:id/delete' => 'dojos#delete', as: 'dojos_delete'
  get 'dojos/:dojo_id/students/new' => 'students#new', as: 'students_new'
  post 'dojos/:dojo_id/students/create' => 'students#create', as: 'students_create'
  get 'dojos/:dojo_id/students/:student_id' => 'students#show', as: 'students_show'
  get 'dojos/:dojo_id/students/:student_id/edit' => 'students#edit', as: 'students_edit'
  patch 'dojos/:dojo_id/students/:student_id/edit' => 'students#update', as: 'students_update'
  delete 'dojos/:dojo_id/students/:student_id/delete' => 'students#delete', as: 'students_delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dojo.rb
class Dojo < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :dojo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dojos_controller.rb
class DojosController < ApplicationController
	def index
		@all_dojos = Dojo.all
		@count = Dojo.count
	end

	def new
	end

	def create
    	new_dojo = Dojo.create(dojo_params)
	    return redirect_to "/dojos" if new_dojo.valid?
    	flash[:errors] = new_dojo.errors.full_messages
    	return redirect_to "/dojos/new"
	end

	def show
		@this_dojo = Dojo.find(params[:id])
		@all_students = Student.where(dojo: params[:id])
		p @all_students
	end

	def edit
		@this_dojo = Dojo.find(params[:id])
	end

	def update
		update_dojo = Dojo.update(params[:id], dojo_params)
		if update_dojo.valid?
			flash[:success] = "Thanks for updating dojo!"
			return redirect_to "/dojos"
		end

		# Otherwise there were errors
		flash[:errors] = update_dojo.errors.full_messages
		redirect_to :back
	end

	def delete
		Dojo.find(params[:id]).destroy
		redirect_to "/dojos"
	end
	private
		def dojo_params
			params.require(:dojo).permit(:branch, :street, :city, :state)
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def show
		@this_student = Student.find(params[:student_id])
		@this_dojo = Dojo.find(params[:dojo_id])
		@these_students = @this_dojo.students.where.not(id: params[:student_id])
	end

	def new
		@this_dojo = Dojo.find(params[:dojo_id])
	end

	def edit
		@this_student = Student.find(params[:student_id])
		@this_dojo = Dojo.find(params[:dojo_id])
		@all_dojos = Dojo.where.not(id: @this_dojo.id)
	end

	def create
    	new_student = Student.create(student_params)
	    if new_student.valid?
	    	return redirect_to "/dojos/#{params[:dojo_id]}" 
	    end 
    	flash[:errors] = new_student.errors.full_messages
    	return redirect_to :back
	end

	def update
		update_student = Student.update(params[:student_id], student_params)
		if update_student.valid?
			return redirect_to "/dojos/#{params[:dojo_id]}/students/#{params[:student_id]}" 
		end
    	flash[:errors] = update_student.errors.full_messages
		redirect_to :back
	end

	def delete
		Student.find(params[:student_id]).destroy
		redirect_to "/dojos/#{params[:dojo_id]}"
	end

	private
		def student_params
			params.require(:student).permit(:first_name, :last_name, :email, :dojo_id)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dojo_controller_helper.rb
module DojoControllerHelper
end

app/helpers/dojos_helper.rb
module DojosHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/dojos/edit.html.erb
<% if flash[:errors] %>	
<div id="alert">
	<% flash[:errors].each do |error| %>	
	<h4><%= error %></h4>
	<% end %>
</div>
<% end %>
<h1> Editing <%= @this_dojo.city %> </h1>
<form action="<%= dojos_update_path(@this_dojo.id) %>" method="POST">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<input type="hidden" name="_method" value="patch">
	<label> Branch: </label>
	<input type="text" name="dojo[branch]" value="<%= @this_dojo.branch %>"> 
	<label> Street: </label>
	<input type="text" name="dojo[street]" value="<%= @this_dojo.street %>">
	<label> City: </label>
	<input type="text" name="dojo[city]" value="<%= @this_dojo.city %>"> 
	<label> State: </label>
	<input type="text" name="dojo[state]" value="<%= @this_dojo.state %>">
	<input type="submit" name="Update">	
</form>
<a href="<%= dojos_new_path %>"> Home </a> | <a href="<%= dojos_show_path(@this_dojo.id) %>">Show</a>

app/views/dojos/index.html.erb
<h1> Listing <%= @count %> Dojos </h1>
<table>
	<thead>
		<th> Coding Dojo Branch </th>
		<th> Street </th>
		<th> City </th>
		<th> State </th>
		<th> Actions </th>
	</thead>
		<tbody>
			<% @all_dojos.each do |dojo| %>
				<tr>
					<td> <%= dojo.branch %> </td>
					<td> <%= dojo.street %> </td>
					<td> <%= dojo.city %> </td>
					<td> <%= dojo.state %> </td>
					<td> <a href="<%= dojos_show_path(dojo.id) %>"> Show </a> | <a href="<%= dojos_edit_path(dojo.id) %>"> Edit </a> | <a href="<%= dojos_delete_path(dojo.id) %> " data-method="delete"> Destroy </a> </td>
					</tr>
				<% end %>
		</tbody>
</table>
<a href="<%= dojos_new_path %>">Add New</a>

app/views/dojos/new.html.erb
<% if flash[:errors] %>	
<div id="alert">
	<% flash[:errors].each do |error| %>	
	<h4><%= error %></h4>
	<% end %>
</div>
	<% end %>
<h1> New Dojo </h1>
<form action="<%= dojos_create_path %>" method="POST">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<label> Branch: </label>
	<input type="text" name="dojo[branch]"> 
	<label> Street: </label>
	<input type="text" name="dojo[street]">
	<label> City: </label>
	<input type="text" name="dojo[city]"> 
	<label> State: </label>
		<input type="text" name="dojo[state]">
		<input type="submit" name="Create">	
</form>
<a href="/"> Home </a>

app/views/dojos/show.html.erb
<div id="dojo_info">
	h1> <%= @this_dojo.city %> Dojo </h1> <a href="<%= dojos_edit_path(@this_dojo.id) %>"> Edit </a>
	<h3> Address: <%= @this_dojo.street %> </h3>
	<h3> City: <%= @this_dojo.city %> State: <%= @this_dojo.state %> </h3>
</div>
<h2> Student Roster </h2>
<table>
	<thead>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Email</th>
		<th>Actions</th>
	</thead>
	<tbody>
		<% @all_students.each do |student| %>
			<tr>
				<td> <%= student.first_name %> </td>
				<td> <%= student.last_name %> </td>
				<td> <%= student.email %> </td>
				<td> <a href="<%= students_show_path(student.dojo_id,student.id) %>"> Show </a> | <a href="<%= students_edit_path(student.dojo_id,student.id) %>"> Edit </a> | <a href="<%= students_delete_path(student.dojo_id,student.id) %>" data-method="delete"> Destroy </a> </td>
			</tr>
			<% end %>
	</tbody>
</table>
<p><a href="<%= dojos_path %>"> Home </a> | <a href="<%= students_new_path(@this_dojo.id) %>"> Add Student </a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DojoDash</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<% if flash[:errors] %>	
<div id="alert">
	<% flash[:errors].each do |error| %>	
	<h4><%= error %></h4>
	<% end %>
</div>
<% end %>
<h1> Editing <%= @this_student.first_name %> <%= @this_student.last_name %> </h1>
<form action="<%= students_update_path(@this_student.dojo_id, @this_student.id) %>" method="POST">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<input type="hidden" name="_method" value="patch">
	<label> First Name: </label>
	<input type="text" name="student[first_name]" value="<%= @this_student.first_name %>"> 
	<label> Last Name: </label>
	<input type="text" name="student[last_name]" value="<%= @this_student.last_name %>">
	<label> Email: </label>
	<input type="text" name="student[email]" value="<%= @this_student.email %>"> 
	<label> Dojo: </label>
	<select>
		<option name="student[dojo_id]" value="@this_dojo.id"> <%= @this_dojo.branch %> </option>
		<% @all_dojos.each do |dojo| %>
		<option name="student[dojo_id]" value="@this_dojo.id"> <%= dojo.branch %> </option>
		<% end %>
	</select>
	<input type="submit" name="Update">	
</form>
<a href="<%= dojos_new_path %>"> Home </a> | <a href="<%= students_show_path(@this_student.dojo_id, @this_student.id) %>"> <%= @this_student.first_name %>'s Page</a>

app/views/students/new.html.erb
<main>
<% if flash[:errors] %>	
    <div id="alert">
        <% flash[:errors].each do |error| %>	
         <h4><%= error %></h4>
         <% end %>
    </div>
<% end %>

<h1> New Student for <%= @this_dojo.branch %> </h1>
<form action="<%= students_create_path(@this_dojo.id) %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label> First Name: </label>
    <input type="text" name="student[first_name]"> 

    <label> Last Name: </label>
    <input type="text" name="student[last_name]">

    <label> Email: </label>
    <input type="text" name="student[email]"> 

    <label> Dojo: </label>
    <select name="student[dojo_id]">
        <option value="<%= @this_dojo.id %>" > <%= @this_dojo.branch %> </option>
    </select>
    <input type="submit" name="Create">	
</form>
<a href="<%= dojos_new_path %>"> Home </a> | <a href="<%= dojos_show_path(@this_dojo.id) %>"> <%= @this_dojo.branch %> </a>
</main>

app/views/students/show.html.erb
<h1> <%= @this_dojo.city %>'s <%= @this_student.first_name %> <%= @this_student.last_name %></h1> 
<div id="student_info">
	<h3> Email: <%= @this_student.email %> </h3>
</div>
<h2> Cohort </h2>
<table>
	<thead>
	<th> First Name </th>
	<th> Last Name </th>
	<th> Email </th>
		<tbody>
		<% @these_students.each do |student| %>
		<tr>
			td> <%= student.first_name %> </td>
			<td> <%= student.last_name %> </td>
			td> <%= student.email %> </td>
		</tr>
		<% end %>
</table>
<p>
<a href="<%= dojos_new_path %>"> Home </a> | <a href="<%= students_edit_path(@this_student.dojo_id, @this_student.id) %>">Edit</a>
</p>